Create Individual Repositories + Services
GhiocelAndrei/IssueTrackerAPI pull request #12
Opened 2023-07-18 15:18 UTC by GhiocelAndrei

This PR solves issues : #6 #8 #9 .
I created individual repositories for each table now my project is structured as follow :
Controller -> Service -> Repository

2023-07-18 16:01 UTC, cristi-paraschiv commented on IssueTrackerApplication/Services/UserService.cs
> +        public async Task<User> PutUser(long id, UserCommandDto userCommand)
looks like Put/Post... (to be rename Create/Update) implementations are identical across services (except for the type argument); what does this indicate?

2023-07-18 16:06 UTC, cristi-paraschiv commented on IssueTrackerApplication/Services/IssueService.cs
> +        private readonly IGenericRepository<Issue> _issueRepository;
you should use the `IssueRepository` explicitly here

2023-07-18 16:32 UTC, cristi-paraschiv requested changes
please address the comments

2023-07-19 08:39 UTC, GhiocelAndrei commented on IssueTrackerAPI/Controllers/IssuesController.cs
>          public async Task<ActionResult<IEnumerable<IssueDto>>> GetIssues()
This will be solved in issue #16

2023-07-19 08:41 UTC, GhiocelAndrei commented on IssueTrackerAPI/Controllers/IssuesController.cs
> +                return BadRequest("Put Issue Failed");
This will be solved in issue #17 .

2023-07-19 09:32 UTC, GhiocelAndrei commented on IssueTrackerAPI/Controllers/IssuesController.cs
> +        private readonly IssueService _issueService;
This issue is solved in the latest commit.

2023-07-19 09:32 UTC, GhiocelAndrei commented on IssueTracker.Abstractions/Mapping/IssueDto.cs
> +    public class IssueCommandDto
This issue is solved in the latest commit.

2023-07-19 09:33 UTC, GhiocelAndrei commented on IssueTrackerApplication/Services/ProjectService.cs
> +        public async Task<Project> PutProject(long id, ProjectCommandDto projectCommand)
Since I am using a Base service class which all other services use I named them : Create, Update. Solved in the latest commit.

2023-07-19 09:34 UTC, GhiocelAndrei commented on IssueTrackerApplication/Services/UserService.cs
> +        public async Task<User> PutUser(long id, UserCommandDto userCommand)
Created base class for all Services.

2023-07-19 09:34 UTC, GhiocelAndrei commented on IssueTrackerDataAccess/Repositories/GenericRepository.cs
> +    public class GenericRepository<T> : IGenericRepository<T> where T : class
This issue is solved in the latest commit.

2023-07-19 09:36 UTC, GhiocelAndrei commented on IssueTrackerApplication/Services/IssueService.cs
> +        private readonly IGenericRepository<Issue> _issueRepository;
Since I am using a Base Service which is using IGenericRepository this shouldn't be solved anymore.

2023-07-19 09:36 UTC, GhiocelAndrei commented on IssueTracker.Abstractions/Mapping/ProjectDto.cs
> +    public class ProjectCommandDto
Solved in the latest commit.

2023-07-19 09:50 UTC, GhiocelAndrei commented on IssueTrackerApplication/Services/IssueService.cs
> +                if (issueModified == null)
Issue solved in the latest commit.

2023-07-19 10:09 UTC, cristi-paraschiv commented on IssueTrackerApplication/Services/BaseService.cs
> +            catch (DbUpdateConcurrencyException)
doesn't really help with anything, remove

2023-07-19 14:20 UTC, florincatrina commented on IssueTrackerDataAccess/Repositories/GenericRepository.cs
> +        public virtual async Task<T> Add(T entity)
All async methods should have Async suffix

2023-07-19 14:20 UTC, florincatrina commented on IssueTrackerDataAccess/Repositories/GenericRepository.cs
> +        public async Task<bool> ExistsWithCondition(Expression<Func<T, bool>> predicate)
async & await can be reduced

2023-07-19 14:20 UTC, florincatrina commented on IssueTrackerDataAccess/Repositories/IssueRepository.cs
> +            var reporterExists = await _dbContext.Users.AnyAsync(u => u.Id == entity.ReporterId);
Exists? or ExistsWithCondition?

2023-07-19 14:20 UTC, florincatrina commented on IssueTrackerDataAccess/Repositories/ProjectRepository.cs
> +    public class ProjectRepository : GenericRepository<Project>
This class doesn't add anything

2023-07-19 14:20 UTC, florincatrina commented on IssueTrackerDataAccess/Repositories/UserRepository.cs
> +    public class UserRepository : GenericRepository<User>
This class doesn't add anything

2023-07-19 15:11 UTC, GhiocelAndrei commented on IssueTrackerDataAccess/Repositories/GenericRepository.cs
> +        public async Task<bool> ExistsWithCondition(Expression<Func<T, bool>> predicate)
Issue solved in the latest commit

2023-07-19 15:12 UTC, GhiocelAndrei commented on IssueTrackerDataAccess/Repositories/ProjectRepository.cs
> +    public class ProjectRepository : GenericRepository<Project>
Since GenericRepository is an abstract class, I am using ProjectRepository as a way to instantiate it.

2023-07-19 15:12 UTC, GhiocelAndrei commented on IssueTrackerDataAccess/Repositories/UserRepository.cs
> +    public class UserRepository : GenericRepository<User>
Since GenericRepository is an abstract class, I am using UserRepository as a way to instantiate it.

2023-07-20 07:54 UTC, florincatrina approved these changes

2023-07-20 10:21 UTC, merged